version: "3.4"
services:
  app:
    image: demo-qnx:deploy-qnx
    ports:
      - "5001:5000"
    depends_on: #wait database start
      - db
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=Admin123
      - POSTGRES_DB=qnx_data
    ports: 
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: